In [29]:
import tensorflow as tf
import keras
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,StratifiedKFold

In [2]:
df_sourceData = pd.read_csv('./广医-现病史.csv')
print(df_sourceData.info())
df_sourceData.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 36 columns):
现病史              2999 non-null object
经常咳嗽_稳定期         2999 non-null object
经常咳嗽时间           2999 non-null object
经常喘息_稳定期         2999 non-null object
经常喘息时间           2999 non-null object
经常胸闷_稳定期         2999 non-null object
经常胸闷时间           2999 non-null object
经常活动后气促_稳定期      2999 non-null object
经常活动后气促时间        2999 non-null object
经常咳痰_稳定期         2999 non-null object
经常咳痰时间           2999 non-null object
经常咳痰痰量           2999 non-null object
诱因_加重期           2999 non-null object
时间_加重期           2999 non-null object
咳嗽_加重期           2999 non-null object
咳嗽_时间            2999 non-null object
咳痰_加重期           2999 non-null object
咳痰_时间            2999 non-null object
胸闷_加重期           2999 non-null object
胸闷_时间            2999 non-null object
喘息_加重期           2999 non-null object
喘息_时间            2999 non-null object
气促_加重期           2999 non-null object
气促_时间            29

现病史 经常咳嗽_稳定期 经常咳嗽时间 经常喘息_稳定期  \
0     患者约10年余前无明显诱因出现活动后气促，伴少咳嗽，咳少量白色粘痰。无胸痛，无发热，无...        有    10年      未提及   
1  患者10日前无明显诱因出现发热，体温最高至39.7度，伴咳嗽咳痰，痰为黄色粘痰，不易咳出，伴...      未提及    未提及      未提及   
2  患者于7余年前无明显反复出现咳嗽、咳痰、气促、心悸，伴夜间阵发性呼吸困难，曾在当地医院就医，...        有     7年      未提及   
3  患者于１年余前活动后出现气促，平素步行至3楼便觉气促，休息后可以缓解，无头晕、头痛，无咳嗽、...        无      无      未提及   
4  患儿于8年前无明显诱因出现咳嗽，非犬吠样咳，咳嗽多于季节转变时加重。6年前出现痰多，为黄色粘...        有     8年      未提及   

  经常喘息时间 经常胸闷_稳定期 经常胸闷时间 经常活动后气促_稳定期 经常活动后气促时间 经常咳痰_稳定期   ...    发热_加重期 发热_时间  \
0    未提及        无      无           有       10年        有   ...         无     无   
1    未提及      未提及    未提及         未提及       未提及      未提及   ...         有   10天   
2    未提及      未提及    未提及         未提及       未提及        有   ...       未提及   未提及   
3    未提及      未提及    未提及           有        1年        无   ...         无     无   
4    未提及      未提及    未提及         未提及       未提及        有   ...         有    5天   

  胸痛_加重期 胸痛_时间 心悸_加重期 心悸_时间 夜间阵发性呼吸困难_加重期 夜间阵发性呼吸困难_时间 双下肢水肿_加重期 双下肢水肿_时间  
0    未提及   未提及    未提及   未提及           未提及          未提及       未提及      未提及  
1      有   10天      无     无           未提及          未提及       未提及      未提及  
2    未提及   未提及    未提及   未提及           未提及          未提及       未提及      未提及  
3    未提及   未提及    未提及   未提及             有           7天       未提及      未提及  
4    未提及   未提及    未提及   未提及           未提及          未提及       未提及      未提及  

[5 rows x 36 columns]

In [3]:
df_sourceData.columns

Index(['现病史', '经常咳嗽_稳定期', '经常咳嗽时间', '经常喘息_稳定期', '经常喘息时间', '经常胸闷_稳定期', '经常胸闷时间',
       '经常活动后气促_稳定期', '经常活动后气促时间', '经常咳痰_稳定期', '经常咳痰时间', '经常咳痰痰量', '诱因_加重期',
       '时间_加重期', '咳嗽_加重期', '咳嗽_时间', '咳痰_加重期', '咳痰_时间', '胸闷_加重期', '胸闷_时间',
       '喘息_加重期', '喘息_时间', '气促_加重期', '气促_时间', '咯血_加重期', '咯血_时间', '发热_加重期',
       '发热_时间', '胸痛_加重期', '胸痛_时间', '心悸_加重期', '心悸_时间', '夜间阵发性呼吸困难_加重期',
       '夜间阵发性呼吸困难_时间', '双下肢水肿_加重期', '双下肢水肿_时间'],
      dtype='object')

In [4]:
df_sourceData = df_sourceData[['现病史','经常咳嗽_稳定期', '经常喘息_稳定期', '经常胸闷_稳定期',
       '经常活动后气促_稳定期', '经常咳痰_稳定期', '咳嗽_加重期', '咳痰_加重期', '胸闷_加重期',
       '喘息_加重期', '气促_加重期', '咯血_加重期', '发热_加重期', '胸痛_加重期', '心悸_加重期', 
        '夜间阵发性呼吸困难_加重期', '双下肢水肿_加重期']]
df_sourceData.head()

现病史 经常咳嗽_稳定期 经常喘息_稳定期  \
0     患者约10年余前无明显诱因出现活动后气促，伴少咳嗽，咳少量白色粘痰。无胸痛，无发热，无...        有      未提及   
1  患者10日前无明显诱因出现发热，体温最高至39.7度，伴咳嗽咳痰，痰为黄色粘痰，不易咳出，伴...      未提及      未提及   
2  患者于7余年前无明显反复出现咳嗽、咳痰、气促、心悸，伴夜间阵发性呼吸困难，曾在当地医院就医，...        有      未提及   
3  患者于１年余前活动后出现气促，平素步行至3楼便觉气促，休息后可以缓解，无头晕、头痛，无咳嗽、...        无      未提及   
4  患儿于8年前无明显诱因出现咳嗽，非犬吠样咳，咳嗽多于季节转变时加重。6年前出现痰多，为黄色粘...        有      未提及   

  经常胸闷_稳定期 经常活动后气促_稳定期 经常咳痰_稳定期 咳嗽_加重期 咳痰_加重期 胸闷_加重期 喘息_加重期 气促_加重期 咯血_加重期  \
0        无           有        有    未提及    未提及      无    未提及    未提及      无   
1      未提及         未提及      未提及      有      有      无    未提及      有    未提及   
2      未提及         未提及        有    未提及    未提及    未提及    未提及    未提及    未提及   
3      未提及           有        无      有      有    未提及    未提及      有    未提及   
4      未提及         未提及        有      有      有    未提及      无      无      有   

  发热_加重期 胸痛_加重期 心悸_加重期 夜间阵发性呼吸困难_加重期 双下肢水肿_加重期  
0      无    未提及    未提及           未提及       未提及  
1      有      有      无           未提及       未提及  
2    未提及    未提及    未提及           未提及       未提及  
3      无    未提及    未提及             有       未提及  
4      有    未提及    未提及           未提及       未提及

In [5]:
list_text = df_sourceData['现病史'].tolist()
print(list_text[:5])

['   患者约10年余前无明显诱因出现活动后气促，伴少咳嗽，咳少量白色粘痰。无胸痛，无发热，无咯血、盗汗、消瘦。间有夜间阵发性呼吸困难，无心悸、胸闷，无双下肢浮肿，无少尿等。5年前于广州军区陆军总医院门诊就诊，拟“慢性阻塞性肺气肿”予“激素”治疗（具体诊治欠详），症状可稍缓解，但气促常反复，未经正规诊治。2年前，患者上述症状再发，气促加重，运动耐量进行性下降，遂来我院门诊就诊，拟“AECOPD”收入我科继续治疗，予激素抗炎、沐舒坦化痰、及氨茶碱和可必特平喘解痉等处理后好转出院。出院后规范用舒利迭等吸入试剂治疗。今年5月份患者因气促加重入住广州市陆军总医院加强治疗，好转后出院。1月前患者诉气促再次加重，活动后明显，咳嗽咳痰较前无明显加重。患者近一个月以来，无发热为，无咯血，无胸闷，无午后低热，胃纳、精神一般，二便正常，体重无明显增减。\n', '患者10日前无明显诱因出现发热，体温最高至39.7度，伴咳嗽咳痰，痰为黄色粘痰，不易咳出，伴右侧胸肋部胸痛，咳嗽时加重，伴气促，活动后加重，伴口干口苦，无畏寒、寒战，无胸闷心悸，无头晕头痛，无恶心呕吐。遂于清远市中医院治疗，当地CT示：考虑右下肺叶炎症并脓肿形成。遂予以退热、抗感染（用过头孢哌酮舒巴坦7天，亚胺培南3天）、化痰、支持等治疗后，患者仍然反复发热，无明显好转。今患者为求进一步诊治入我院求诊，门诊以“右肺炎并脓肿”收住我科。入院后患者精神、食欲、睡眠一般，小便无异常，可见褐色大便。起病来患者体重无明显增减。', '患者于7余年前无明显反复出现咳嗽、咳痰、气促、心悸，伴夜间阵发性呼吸困难，曾在当地医院就医，诊断为“冠心病 陈旧性心肌梗死 ”，经治疗（具体不详）好转后出院。2月前上述症状加重，休息时既有发作，夜间不能平卧，无双下肢浮肿，即到当地医院住院治疗，予以对症治疗后症状好转，但出院后上诉症状反复发作，伴夜间阵发性呼吸困难及端坐呼吸，体力活动明显受限，伴咳嗽，咳痰，为白色稀痰，无血丝痰，无双下肢浮肿。无畏寒、发热，无恶心、呕吐，见有胸痛、心悸，无黑朦、晕厥、抽搐，为求进一步诊治入我院就医，门诊以“冠心病”收入我科治疗。患者起病以来，饮食稍差，睡眠一般，大小便正常，体重无明显改变。\n', '患者于１年余前活动后出现气促，平素步行至3楼便觉气促，休息后可以缓解，无头晕、头痛，无咳嗽、咳痰，无恶心、呕吐,间中端坐呼吸，

In [6]:
df_label = df_sourceData[['经常咳嗽_稳定期', '经常喘息_稳定期', '经常胸闷_稳定期',
       '经常活动后气促_稳定期', '经常咳痰_稳定期', '咳嗽_加重期', '咳痰_加重期', '胸闷_加重期',
       '喘息_加重期', '气促_加重期', '咯血_加重期', '发热_加重期', '胸痛_加重期', '心悸_加重期', 
        '夜间阵发性呼吸困难_加重期', '双下肢水肿_加重期']]
df_label.head()

经常咳嗽_稳定期 经常喘息_稳定期 经常胸闷_稳定期 经常活动后气促_稳定期 经常咳痰_稳定期 咳嗽_加重期 咳痰_加重期 胸闷_加重期 喘息_加重期  \
0        有      未提及        无           有        有    未提及    未提及      无    未提及   
1      未提及      未提及      未提及         未提及      未提及      有      有      无    未提及   
2        有      未提及      未提及         未提及        有    未提及    未提及    未提及    未提及   
3        无      未提及      未提及           有        无      有      有    未提及    未提及   
4        有      未提及      未提及         未提及        有      有      有    未提及      无   

  气促_加重期 咯血_加重期 发热_加重期 胸痛_加重期 心悸_加重期 夜间阵发性呼吸困难_加重期 双下肢水肿_加重期  
0    未提及      无      无    未提及    未提及           未提及       未提及  
1      有    未提及      有      有      无           未提及       未提及  
2    未提及    未提及    未提及    未提及    未提及           未提及       未提及  
3      有    未提及      无    未提及    未提及             有       未提及  
4      无      有      有    未提及    未提及           未提及       未提及

In [7]:
list_nodeName = list(df_label.columns)
print(list_nodeName)

['经常咳嗽_稳定期', '经常喘息_稳定期', '经常胸闷_稳定期', '经常活动后气促_稳定期', '经常咳痰_稳定期', '咳嗽_加重期', '咳痰_加重期', '胸闷_加重期', '喘息_加重期', '气促_加重期', '咯血_加重期', '发热_加重期', '胸痛_加重期', '心悸_加重期', '夜间阵发性呼吸困难_加重期', '双下肢水肿_加重期']


In [8]:
list_nodeValue = ['未提及','有','无']

In [9]:
for i in range(len(list_nodeValue)):
    df_label.replace(list_nodeValue[i], i, inplace=True)
    
print(df_label.head())

   经常咳嗽_稳定期  经常喘息_稳定期  经常胸闷_稳定期  经常活动后气促_稳定期  经常咳痰_稳定期  咳嗽_加重期  咳痰_加重期  \
0         1         0         2            1         1       0       0   
1         0         0         0            0         0       1       1   
2         1         0         0            0         1       0       0   
3         2         0         0            1         2       1       1   
4         1         0         0            0         1       1       1   

   胸闷_加重期  喘息_加重期  气促_加重期  咯血_加重期  发热_加重期  胸痛_加重期  心悸_加重期  夜间阵发性呼吸困难_加重期  \
0       2       0       0       2       2       0       0              0   
1       2       0       1       0       1       1       2              0   
2       0       0       0       0       0       0       0              0   
3       0       0       1       0       2       0       0              1   
4       0       2       2       1       1       0       0              0   

   双下肢水肿_加重期  
0          0  
1          0  
2          0  
3          0  
4          0  


/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3798: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)


In [10]:
# from bert_serving.client import BertClient
# bc = BertClient(ip='localhost') 

In [11]:
# list_vecOfText = bc.encode(list_text)

# print(len(list_vecOfText))
# print(len(list_vecOfText[0]))
# print(list_vecOfText[:5])

# import pickle
# file = open('list_bertVecOf3000GuangYiXianBingShiText.pkl','wb')
# pickle.dump(list_vecOfText, file)
# file.close()

2999
768
[[ 0.3642559   0.0403133  -0.08496993 ...  0.54027784 -0.7236914
   0.3691523 ]
 [ 0.48475075 -0.04703546  0.1383034  ...  0.89154756 -0.31899124
   0.37009084]
 [ 0.66620576 -0.16416909 -0.09690358 ...  0.4910622  -0.52844286
   0.06622208]
 [ 0.50481075  0.01123063  0.2735827  ...  0.4039476  -0.3995528
   0.15207668]
 [ 0.37577748 -0.23518471 -0.05861272 ...  0.62255365 -0.50356174
   0.52458566]]


In [10]:
import pickle

with open('list_bertVecOf3000GuangYiXianBingShiText.pkl','rb') as file:
    list_vecOfText = pickle.load(file)
    
print(len(list_vecOfText))
print(len(list_vecOfText[0]))
print(list_vecOfText[:5])

2999
768
[[ 0.3642559   0.0403133  -0.08496993 ...  0.54027784 -0.7236914
   0.3691523 ]
 [ 0.48475075 -0.04703546  0.1383034  ...  0.89154756 -0.31899124
   0.37009084]
 [ 0.66620576 -0.16416909 -0.09690358 ...  0.4910622  -0.52844286
   0.06622208]
 [ 0.50481075  0.01123063  0.2735827  ...  0.4039476  -0.3995528
   0.15207668]
 [ 0.37577748 -0.23518471 -0.05861272 ...  0.62255365 -0.50356174
   0.52458566]]


In [11]:
import matplotlib.pyplot as plt
%matplotlib inline

class LossHistory(keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.losses = {'batch':[], 'epoch':[]}
        self.accuracy = {'batch':[], 'epoch':[]}
        self.val_loss = {'batch':[], 'epoch':[]}
        self.val_acc = {'batch':[], 'epoch':[]}

    def on_batch_end(self, batch, logs={}):
        self.losses['batch'].append(logs.get('loss'))
        self.accuracy['batch'].append(logs.get('acc'))
        self.val_loss['batch'].append(logs.get('val_loss'))
        self.val_acc['batch'].append(logs.get('val_acc'))

    def on_epoch_end(self, batch, logs={}):
        self.losses['epoch'].append(logs.get('loss'))
        self.accuracy['epoch'].append(logs.get('acc'))
        self.val_loss['epoch'].append(logs.get('val_loss'))
        self.val_acc['epoch'].append(logs.get('val_acc'))

    def loss_plot(self, loss_type):
        iters = range(len(self.losses[loss_type]))
        plt.figure()
        # acc
        plt.plot(iters, self.accuracy[loss_type], 'r', label='train acc')
        # loss
        plt.plot(iters, self.losses[loss_type], 'g', label='train loss')
        if loss_type == 'epoch':
            # val_acc
            plt.plot(iters, self.val_acc[loss_type], 'b', label='val acc')
            # val_loss
            plt.plot(iters, self.val_loss[loss_type], 'k', label='val loss')
        plt.grid(True)
        plt.xlabel(loss_type)
        plt.ylabel('acc-loss')
        plt.legend(loc="upper right")
        plt.show()

In [12]:
# matrix_label01 = np.array(df_label['经常咳嗽_稳定期'])[:,:3]
matrix_label_mention = []
for i in range(len(list_nodeName)):
    list_label_column = np.array(df_label.iloc[:,i])
    list_label_column_mention = np.array(list(map(lambda x:0 if x==0 else 1, list_label_column)))
    matrix_label_mention.append(list_label_column_mention)

matrix_label_mention = np.array(matrix_label_mention)
print(len(matrix_label_mention))
print(len(matrix_label_mention[0]))
print(matrix_label_mention[:3])

16
2999
[[1 0 1 ... 1 0 1]
 [0 0 0 ... 0 0 1]
 [1 0 0 ... 1 1 0]]


In [19]:
from sklearn.model_selection import LeaveOneOut,KFold

# import tensorflow.contrib.eager as tfe
# tf.enable_eager_execution()


# def make_dataset(X_data,y_data,n_splits):
#     def gen():
#         for train_index, test_index in KFold(n_splits).split(X_data):
#             X_train, X_test = X_data[train_index], X_data[test_index]
#             y_train, y_test = y_data[train_index], y_data[test_index]
#             yield X_train,y_train,X_test,y_test

#     return tf.data.Dataset.from_generator(gen, (tf.float64,tf.float64,tf.float64,tf.float64))


# 使用示例
# iter_ds = dataset.make_one_shot_iterator()
# value = iter_ds.get_next()
# print(value)

# iii = 0
# for X_train,y_train,X_test,y_test in tfe.Iterator(dataset):
#     print(iii)
#     iii += 1


In [38]:
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers

kValue_of_KFold = 3
list_model_mention = []
matrix_score_mention = []
matrix_history_mention = []

for i in range(len(list_nodeName)):    
#     model_mention = Sequential()
#     model_mention.add(Dense(units=256, activation='relu', input_dim=len(list_vecOfText[0])))
#     model_mention.add(Dense(units=128, activation='relu'))
#     model_mention.add(Dense(units=64, activation='relu'))
#     model_mention.add(Dense(units=1, activation='sigmoid'))

#     model_mention.compile(loss='binary_crossentropy',
#                   optimizer=optimizers.RMSprop(),
#                   metrics=['accuracy'])

# #     print(model_mention.summary())

#     check_point_mention = keras.callbacks.ModelCheckpoint('./CheckPoint/guangyi3000xianbingshi/guangyi3000xianbingshi_modelMentionmention{}_checkpoint.hdf5'.format(i), monitor='val_loss', verbose=0, 
#                                                   save_best_only=True, save_weights_only=False, mode='auto', period=1)
#     early_stop_mention = keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=30, verbose=0,
#                                   mode='auto', baseline=None, restore_best_weights=False)
#     #创建一个实例history
#     history_mention = LossHistory()
#     callbacks_mention = [check_point_mention, early_stop_mention,history_mention]

#     def classifier(input_shape):
#         """classifier network.
#         Args:
#         input_shape: the desired input shape (e.g.: (latent_space_size))
#         Returns:
#         C: The classifier model
#         """
#         inputs = tf.keras.layers.Input(input_shape)
#         net = tf.keras.layers.Dense(units=256, activation=tf.nn.elu, name="fc1")(inputs)
#         net = tf.keras.layers.Dense(units=128, activation=tf.nn.elu, name="fc2")(net)
#         net = tf.keras.layers.Dense(units=64, activation=tf.nn.elu, name="fc3")(net)
#         net = tf.keras.layers.Dense(units=1, activation=tf.nn.softmax, name="C")(net)
#         C = tf.keras.Model(inputs=inputs, outputs=net)
#         return C

    
    X = np.array(list_vecOfText)
    y = np.array(matrix_label_mention[i])
    
    list_score_mention = []
    list_history_mention = []
    ii = 0
    for train_index, test_index in KFold(kValue_of_KFold).split(X):
        model_mention = Sequential()
        model_mention.add(Dense(units=256, activation='relu', input_dim=len(list_vecOfText[0])))
        model_mention.add(Dense(units=128, activation='relu'))
        model_mention.add(Dense(units=64, activation='relu'))
        model_mention.add(Dense(units=1, activation='sigmoid'))

        model_mention.compile(loss='binary_crossentropy',
                      optimizer=optimizers.RMSprop(),
                      metrics=['accuracy'])

    #     print(model_mention.summary())

        check_point_mention = keras.callbacks.ModelCheckpoint('./CheckPoint/guangyi3000xianbingshi/guangyi3000xianbingshi_modelMentionmention{}_checkpoint.hdf5'.format(i), monitor='val_loss', verbose=0, 
                                                      save_best_only=True, save_weights_only=False, mode='auto', period=1)
        early_stop_mention = keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=30, verbose=0,
                                      mode='auto', baseline=None, restore_best_weights=False)
        #创建一个实例history
        history_mention = LossHistory()
        callbacks_mention = [check_point_mention, early_stop_mention,history_mention]
        
        
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        model_mention.fit(X_train, y_train, epochs=1000, batch_size=32,
                     callbacks=callbacks_mention, validation_split=0.2)

        score_mention = model_mention.evaluate(X_test, y_test, verbose=0)
        print('\n{}.{})Test loss of feature:{} Fold:{} :'.format(i,ii,list_nodeName[i],ii), score_mention[0])
        print('{}.{})Test accuracy of feature:{} Fold:{} :'.format(i,ii,list_nodeName[i], ii), score_mention[1])
        print('\n\n\n')
        list_score_mention.append(score_mention)
        
        #绘制acc-loss曲线
#         history_mention.loss_plot('epoch')
        list_history_mention.append(history_mention)

        # predict_mention = model_mention.predict(np.array(list_vecOfNodeText))
        # print(predict_mention)
        # print(matrix_labelmention)
        ii += 1
    
    list_model_mention.append(model_mention)
    matrix_score_mention.append(list_score_mention)
    matrix_history_mention.append(list_history_mention)

Train on 1599 samples, validate on 400 samples
Epoch 1/1000
1599/1599 [==============================] - 2s 945us/step - loss: 0.4228 - acc: 0.8211 - val_loss: 0.2785 - val_acc: 0.8875
Epoch 2/1000
1599/1599 [==============================] - 0s 164us/step - loss: 0.3154 - acc: 0.8612 - val_loss: 0.2880 - val_acc: 0.9025
Epoch 3/1000
1599/1599 [==============================] - 0s 165us/step - loss: 0.2722 - acc: 0.8856 - val_loss: 0.3004 - val_acc: 0.8600
Epoch 4/1000
1599/1599 [==============================] - 0s 166us/step - loss: 0.2620 - acc: 0.8868 - val_loss: 0.2976 - val_acc: 0.8825
Epoch 5/1000
1599/1599 [==============================] - 0s 166us/step - loss: 0.2394 - acc: 0.8912 - val_loss: 0.2665 - val_acc: 0.9000
Epoch 6/1000
1599/1599 [==============================] - 0s 160us/step - loss: 0.2300 - acc: 0.9037 - val_loss: 0.2817 - val_acc: 0.8975
Epoch 7/1000
1599/1599 [==============================] - 0s 171us/step - loss: 0.2114 - acc: 0.9118 - val_loss: 0.2926 - val

1599/1599 [==============================] - 0s 166us/step - loss: 0.1259 - acc: 0.9468 - val_loss: 0.4699 - val_acc: 0.9175
Epoch 21/1000
1599/1599 [==============================] - 0s 205us/step - loss: 0.1191 - acc: 0.9462 - val_loss: 0.3830 - val_acc: 0.8950
Epoch 22/1000
1599/1599 [==============================] - 0s 262us/step - loss: 0.1265 - acc: 0.9493 - val_loss: 0.4631 - val_acc: 0.8825
Epoch 23/1000
1599/1599 [==============================] - 0s 214us/step - loss: 0.1047 - acc: 0.9587 - val_loss: 0.4873 - val_acc: 0.9050
Epoch 24/1000
1599/1599 [==============================] - 0s 169us/step - loss: 0.1302 - acc: 0.9537 - val_loss: 0.4163 - val_acc: 0.8875
Epoch 25/1000
1599/1599 [==============================] - 0s 195us/step - loss: 0.1087 - acc: 0.9537 - val_loss: 0.4321 - val_acc: 0.8800
Epoch 26/1000
1599/1599 [==============================] - 0s 173us/step - loss: 0.1002 - acc: 0.9612 - val_loss: 0.5199 - val_acc: 0.9200
Epoch 27/1000
1599/1599 [================

Epoch 37/1000
1600/1600 [==============================] - 0s 248us/step - loss: 0.0719 - acc: 0.9781 - val_loss: 0.6397 - val_acc: 0.8975
Epoch 38/1000
1600/1600 [==============================] - 0s 246us/step - loss: 0.0512 - acc: 0.9800 - val_loss: 0.6257 - val_acc: 0.8775

0.2)Test loss of feature:经常咳嗽_稳定期 Fold:2 : 0.7338237175652692
0.2)Test accuracy of feature:经常咳嗽_稳定期 Fold:2 : 0.8658658659255302




Train on 1599 samples, validate on 400 samples
Epoch 1/1000
1599/1599 [==============================] - 2s 1ms/step - loss: 0.4541 - acc: 0.8230 - val_loss: 0.4447 - val_acc: 0.8500
Epoch 2/1000
1599/1599 [==============================] - 0s 187us/step - loss: 0.4280 - acc: 0.8318 - val_loss: 0.4542 - val_acc: 0.8500
Epoch 3/1000
1599/1599 [==============================] - 0s 204us/step - loss: 0.4230 - acc: 0.8318 - val_loss: 0.4015 - val_acc: 0.8500
Epoch 4/1000
1599/1599 [==============================] - 0s 252us/step - loss: 0.3990 - acc: 0.8299 - val_loss: 0.4337 - val_acc:


1.0)Test loss of feature:经常喘息_稳定期 Fold:0 : 0.720489734172821
1.0)Test accuracy of feature:经常喘息_稳定期 Fold:0 : 0.838




Train on 1599 samples, validate on 400 samples
Epoch 1/1000
1599/1599 [==============================] - 2s 1ms/step - loss: 0.4600 - acc: 0.8255 - val_loss: 0.4376 - val_acc: 0.8500
Epoch 2/1000
1599/1599 [==============================] - 0s 194us/step - loss: 0.4305 - acc: 0.8343 - val_loss: 0.4488 - val_acc: 0.8500
Epoch 3/1000
1599/1599 [==============================] - 0s 223us/step - loss: 0.4197 - acc: 0.8343 - val_loss: 0.4134 - val_acc: 0.8500
Epoch 4/1000
1599/1599 [==============================] - 0s 210us/step - loss: 0.4164 - acc: 0.8343 - val_loss: 0.4132 - val_acc: 0.8500
Epoch 5/1000
1599/1599 [==============================] - 0s 218us/step - loss: 0.4087 - acc: 0.8361 - val_loss: 0.4088 - val_acc: 0.8525
Epoch 6/1000
1599/1599 [==============================] - 0s 215us/step - loss: 0.4012 - acc: 0.8374 - val_loss: 0.4044 - val_acc: 0.8500
Epoch 7/

Epoch 21/1000
1600/1600 [==============================] - 0s 237us/step - loss: 0.3179 - acc: 0.8713 - val_loss: 0.6019 - val_acc: 0.8500
Epoch 22/1000
1600/1600 [==============================] - 0s 226us/step - loss: 0.3241 - acc: 0.8688 - val_loss: 0.6941 - val_acc: 0.8450
Epoch 23/1000
1600/1600 [==============================] - 0s 248us/step - loss: 0.3382 - acc: 0.8588 - val_loss: 0.5429 - val_acc: 0.8450
Epoch 24/1000
1600/1600 [==============================] - 0s 233us/step - loss: 0.3179 - acc: 0.8644 - val_loss: 0.4974 - val_acc: 0.8500
Epoch 25/1000
1600/1600 [==============================] - 0s 216us/step - loss: 0.3179 - acc: 0.8619 - val_loss: 0.5693 - val_acc: 0.8500
Epoch 26/1000
1600/1600 [==============================] - 0s 209us/step - loss: 0.3211 - acc: 0.8625 - val_loss: 0.6649 - val_acc: 0.8425
Epoch 27/1000
1600/1600 [==============================] - 0s 214us/step - loss: 0.3153 - acc: 0.8669 - val_loss: 0.5513 - val_acc: 0.8450
Epoch 28/1000
1600/1600 [==

1599/1599 [==============================] - 0s 229us/step - loss: 0.5822 - acc: 0.6879 - val_loss: 0.6559 - val_acc: 0.6475
Epoch 9/1000
1599/1599 [==============================] - 0s 212us/step - loss: 0.5780 - acc: 0.6917 - val_loss: 0.6243 - val_acc: 0.6675
Epoch 10/1000
1599/1599 [==============================] - 0s 219us/step - loss: 0.5807 - acc: 0.7073 - val_loss: 0.6410 - val_acc: 0.6675
Epoch 11/1000
1599/1599 [==============================] - 0s 207us/step - loss: 0.5728 - acc: 0.7129 - val_loss: 0.6273 - val_acc: 0.6675
Epoch 12/1000
1599/1599 [==============================] - 0s 215us/step - loss: 0.5771 - acc: 0.7054 - val_loss: 0.6364 - val_acc: 0.6500
Epoch 13/1000
1599/1599 [==============================] - 0s 220us/step - loss: 0.5509 - acc: 0.7061 - val_loss: 0.7142 - val_acc: 0.6575
Epoch 14/1000
1599/1599 [==============================] - 0s 209us/step - loss: 0.5504 - acc: 0.7186 - val_loss: 0.6362 - val_acc: 0.6675
Epoch 15/1000
1599/1599 [=================

Epoch 27/1000
1600/1600 [==============================] - 0s 227us/step - loss: 0.4727 - acc: 0.7556 - val_loss: 0.6414 - val_acc: 0.6525
Epoch 28/1000
1600/1600 [==============================] - 0s 219us/step - loss: 0.4594 - acc: 0.7769 - val_loss: 0.6342 - val_acc: 0.6975
Epoch 29/1000
1600/1600 [==============================] - 0s 209us/step - loss: 0.4729 - acc: 0.7625 - val_loss: 0.6402 - val_acc: 0.7000
Epoch 30/1000
1600/1600 [==============================] - 0s 213us/step - loss: 0.4531 - acc: 0.7606 - val_loss: 0.6451 - val_acc: 0.7050
Epoch 31/1000
1600/1600 [==============================] - 0s 203us/step - loss: 0.4531 - acc: 0.7806 - val_loss: 0.6723 - val_acc: 0.6925
Epoch 32/1000
1600/1600 [==============================] - 0s 217us/step - loss: 0.4571 - acc: 0.7800 - val_loss: 0.7495 - val_acc: 0.6950
Epoch 33/1000
1600/1600 [==============================] - 0s 216us/step - loss: 0.4616 - acc: 0.7706 - val_loss: 0.7895 - val_acc: 0.7125
Epoch 34/1000
1600/1600 [==

1599/1599 [==============================] - 0s 237us/step - loss: 0.4534 - acc: 0.7980 - val_loss: 0.6139 - val_acc: 0.7275
Epoch 12/1000
1599/1599 [==============================] - 0s 220us/step - loss: 0.4454 - acc: 0.8074 - val_loss: 0.5927 - val_acc: 0.7375
Epoch 13/1000
1599/1599 [==============================] - 0s 228us/step - loss: 0.4471 - acc: 0.8080 - val_loss: 0.5540 - val_acc: 0.7550
Epoch 14/1000
1599/1599 [==============================] - 0s 216us/step - loss: 0.4250 - acc: 0.8136 - val_loss: 0.5939 - val_acc: 0.7775
Epoch 15/1000
1599/1599 [==============================] - 0s 227us/step - loss: 0.4111 - acc: 0.8293 - val_loss: 0.6381 - val_acc: 0.6975
Epoch 16/1000
1599/1599 [==============================] - 0s 224us/step - loss: 0.4343 - acc: 0.8111 - val_loss: 0.5878 - val_acc: 0.7675
Epoch 17/1000
1599/1599 [==============================] - 0s 215us/step - loss: 0.4115 - acc: 0.8218 - val_loss: 0.6057 - val_acc: 0.7500
Epoch 18/1000
1599/1599 [================

1600/1600 [==============================] - 0s 231us/step - loss: 0.3548 - acc: 0.8450 - val_loss: 0.6670 - val_acc: 0.7450
Epoch 35/1000
1600/1600 [==============================] - 0s 238us/step - loss: 0.3390 - acc: 0.8462 - val_loss: 0.6996 - val_acc: 0.7550
Epoch 36/1000
1600/1600 [==============================] - 0s 265us/step - loss: 0.3513 - acc: 0.8469 - val_loss: 0.6136 - val_acc: 0.7450
Epoch 37/1000
1600/1600 [==============================] - 1s 331us/step - loss: 0.3353 - acc: 0.8512 - val_loss: 0.8593 - val_acc: 0.7475
Epoch 38/1000
1600/1600 [==============================] - 0s 255us/step - loss: 0.3293 - acc: 0.8444 - val_loss: 0.8117 - val_acc: 0.7500
Epoch 39/1000
1600/1600 [==============================] - 0s 210us/step - loss: 0.3616 - acc: 0.8512 - val_loss: 0.7644 - val_acc: 0.7775
Epoch 40/1000
1600/1600 [==============================] - 0s 259us/step - loss: 0.3097 - acc: 0.8631 - val_loss: 0.7160 - val_acc: 0.7075
Epoch 41/1000
1600/1600 [================

1599/1599 [==============================] - 0s 234us/step - loss: 0.2212 - acc: 0.9043 - val_loss: 0.2905 - val_acc: 0.8825
Epoch 14/1000
1599/1599 [==============================] - 0s 287us/step - loss: 0.2044 - acc: 0.9031 - val_loss: 0.3704 - val_acc: 0.8975
Epoch 15/1000
1599/1599 [==============================] - 0s 305us/step - loss: 0.2145 - acc: 0.9049 - val_loss: 0.3300 - val_acc: 0.8800
Epoch 16/1000
1599/1599 [==============================] - 0s 279us/step - loss: 0.2046 - acc: 0.9087 - val_loss: 0.3325 - val_acc: 0.8950
Epoch 17/1000
1599/1599 [==============================] - 0s 241us/step - loss: 0.1802 - acc: 0.9206 - val_loss: 0.4558 - val_acc: 0.8600
Epoch 18/1000
1599/1599 [==============================] - 0s 225us/step - loss: 0.1873 - acc: 0.9212 - val_loss: 0.5504 - val_acc: 0.8825
Epoch 19/1000
1599/1599 [==============================] - 0s 224us/step - loss: 0.1787 - acc: 0.9243 - val_loss: 0.3802 - val_acc: 0.9050
Epoch 20/1000
1599/1599 [================


4.2)Test loss of feature:经常咳痰_稳定期 Fold:2 : 0.9279757921879476
4.2)Test accuracy of feature:经常咳痰_稳定期 Fold:2 : 0.8388388390178317




Train on 1599 samples, validate on 400 samples
Epoch 1/1000
1599/1599 [==============================] - 2s 1ms/step - loss: 0.6693 - acc: 0.6435 - val_loss: 0.6163 - val_acc: 0.6875
Epoch 2/1000
1599/1599 [==============================] - 0s 176us/step - loss: 0.6223 - acc: 0.6654 - val_loss: 0.6350 - val_acc: 0.6575
Epoch 3/1000
1599/1599 [==============================] - 0s 234us/step - loss: 0.6168 - acc: 0.6679 - val_loss: 0.6116 - val_acc: 0.6825
Epoch 4/1000
1599/1599 [==============================] - 0s 181us/step - loss: 0.6064 - acc: 0.6767 - val_loss: 0.6080 - val_acc: 0.6825
Epoch 5/1000
1599/1599 [==============================] - 0s 193us/step - loss: 0.6094 - acc: 0.6823 - val_loss: 0.6339 - val_acc: 0.6625
Epoch 6/1000
1599/1599 [==============================] - 0s 231us/step - loss: 0.5918 - acc: 0.6936 - val_loss: 0.6182 - val_acc: 0

1599/1599 [==============================] - 1s 349us/step - loss: 0.4956 - acc: 0.7724 - val_loss: 0.7071 - val_acc: 0.6725
Epoch 24/1000
1599/1599 [==============================] - 1s 335us/step - loss: 0.4750 - acc: 0.7817 - val_loss: 0.7088 - val_acc: 0.6600
Epoch 25/1000
1599/1599 [==============================] - 0s 263us/step - loss: 0.4587 - acc: 0.7880 - val_loss: 0.8663 - val_acc: 0.6675
Epoch 26/1000
1599/1599 [==============================] - 0s 215us/step - loss: 0.4634 - acc: 0.7930 - val_loss: 0.7570 - val_acc: 0.6850
Epoch 27/1000
1599/1599 [==============================] - 0s 204us/step - loss: 0.4596 - acc: 0.7867 - val_loss: 0.7253 - val_acc: 0.6675
Epoch 28/1000
1599/1599 [==============================] - 0s 200us/step - loss: 0.4475 - acc: 0.8055 - val_loss: 0.7584 - val_acc: 0.6825
Epoch 29/1000
1599/1599 [==============================] - 0s 219us/step - loss: 0.4534 - acc: 0.7892 - val_loss: 0.8446 - val_acc: 0.6700
Epoch 30/1000
1599/1599 [================


5.2)Test loss of feature:咳嗽_加重期 Fold:2 : 0.8914166415059889
5.2)Test accuracy of feature:咳嗽_加重期 Fold:2 : 0.6776776777970063




Train on 1599 samples, validate on 400 samples
Epoch 1/1000
1599/1599 [==============================] - 3s 2ms/step - loss: 0.6732 - acc: 0.6241 - val_loss: 0.6293 - val_acc: 0.6800
Epoch 2/1000
1599/1599 [==============================] - 0s 283us/step - loss: 0.6263 - acc: 0.6629 - val_loss: 0.6111 - val_acc: 0.6875
Epoch 3/1000
1599/1599 [==============================] - 0s 238us/step - loss: 0.6211 - acc: 0.6754 - val_loss: 0.6099 - val_acc: 0.7025
Epoch 4/1000
1599/1599 [==============================] - 0s 216us/step - loss: 0.6216 - acc: 0.6685 - val_loss: 0.6206 - val_acc: 0.6975
Epoch 5/1000
1599/1599 [==============================] - 0s 198us/step - loss: 0.6129 - acc: 0.6817 - val_loss: 0.6261 - val_acc: 0.6775
Epoch 6/1000
1599/1599 [==============================] - 0s 205us/step - loss: 0.6141 - acc: 0.6785 - val_loss: 0.6552 - val_acc: 0.627

1599/1599 [==============================] - 0s 202us/step - loss: 0.4809 - acc: 0.7736 - val_loss: 0.7158 - val_acc: 0.6850
Epoch 20/1000
1599/1599 [==============================] - 0s 279us/step - loss: 0.4699 - acc: 0.7799 - val_loss: 0.7603 - val_acc: 0.6850
Epoch 21/1000
1599/1599 [==============================] - 0s 269us/step - loss: 0.4758 - acc: 0.7836 - val_loss: 0.6781 - val_acc: 0.6950
Epoch 22/1000
1599/1599 [==============================] - 0s 264us/step - loss: 0.4499 - acc: 0.7930 - val_loss: 0.7929 - val_acc: 0.6950
Epoch 23/1000
1599/1599 [==============================] - 0s 221us/step - loss: 0.4633 - acc: 0.7930 - val_loss: 0.7770 - val_acc: 0.6450
Epoch 24/1000
1599/1599 [==============================] - 0s 302us/step - loss: 0.4510 - acc: 0.7849 - val_loss: 0.7554 - val_acc: 0.6700
Epoch 25/1000
1599/1599 [==============================] - 0s 274us/step - loss: 0.4477 - acc: 0.7999 - val_loss: 0.7231 - val_acc: 0.6825
Epoch 26/1000
1599/1599 [================

Epoch 38/1000
1600/1600 [==============================] - 0s 220us/step - loss: 0.4403 - acc: 0.8056 - val_loss: 1.0533 - val_acc: 0.6075
Epoch 39/1000
1600/1600 [==============================] - 0s 206us/step - loss: 0.4480 - acc: 0.8031 - val_loss: 0.7815 - val_acc: 0.6625

6.2)Test loss of feature:咳痰_加重期 Fold:2 : 0.8357854886455937
6.2)Test accuracy of feature:咳痰_加重期 Fold:2 : 0.6386386387579672




Train on 1599 samples, validate on 400 samples
Epoch 1/1000
1599/1599 [==============================] - 2s 2ms/step - loss: 0.7122 - acc: 0.5904 - val_loss: 0.6810 - val_acc: 0.6200
Epoch 2/1000
1599/1599 [==============================] - 0s 193us/step - loss: 0.6792 - acc: 0.5916 - val_loss: 0.6658 - val_acc: 0.6200
Epoch 3/1000
1599/1599 [==============================] - 0s 197us/step - loss: 0.6647 - acc: 0.6148 - val_loss: 0.6564 - val_acc: 0.6200
Epoch 4/1000
1599/1599 [==============================] - 0s 217us/step - loss: 0.6639 - acc: 0.6129 - val_loss: 0.6649 - val_acc: 0.6

1599/1599 [==============================] - 0s 211us/step - loss: 0.5955 - acc: 0.6704 - val_loss: 0.7810 - val_acc: 0.6275
Epoch 16/1000
1599/1599 [==============================] - 0s 200us/step - loss: 0.5885 - acc: 0.6767 - val_loss: 0.7507 - val_acc: 0.6225
Epoch 17/1000
1599/1599 [==============================] - 0s 211us/step - loss: 0.5825 - acc: 0.6804 - val_loss: 0.7300 - val_acc: 0.6200
Epoch 18/1000
1599/1599 [==============================] - 0s 201us/step - loss: 0.5611 - acc: 0.6948 - val_loss: 0.8951 - val_acc: 0.5725
Epoch 19/1000
1599/1599 [==============================] - 0s 216us/step - loss: 0.5802 - acc: 0.6760 - val_loss: 0.8929 - val_acc: 0.5950
Epoch 20/1000
1599/1599 [==============================] - 0s 211us/step - loss: 0.5842 - acc: 0.6823 - val_loss: 0.9154 - val_acc: 0.6200
Epoch 21/1000
1599/1599 [==============================] - 0s 206us/step - loss: 0.5769 - acc: 0.6873 - val_loss: 0.8113 - val_acc: 0.6100
Epoch 22/1000
1599/1599 [================

1599/1599 [==============================] - 3s 2ms/step - loss: 0.3764 - acc: 0.8724 - val_loss: 0.2793 - val_acc: 0.9200
Epoch 2/1000
1599/1599 [==============================] - 0s 181us/step - loss: 0.3435 - acc: 0.8856 - val_loss: 0.2685 - val_acc: 0.9200
Epoch 3/1000
1599/1599 [==============================] - 0s 192us/step - loss: 0.3519 - acc: 0.8856 - val_loss: 0.2813 - val_acc: 0.9200
Epoch 4/1000
1599/1599 [==============================] - 0s 232us/step - loss: 0.3372 - acc: 0.8856 - val_loss: 0.2756 - val_acc: 0.9200
Epoch 5/1000
1599/1599 [==============================] - 0s 217us/step - loss: 0.3344 - acc: 0.8856 - val_loss: 0.2679 - val_acc: 0.9200
Epoch 6/1000
1599/1599 [==============================] - 0s 218us/step - loss: 0.3290 - acc: 0.8856 - val_loss: 0.2923 - val_acc: 0.9200
Epoch 7/1000
1599/1599 [==============================] - 0s 247us/step - loss: 0.3296 - acc: 0.8856 - val_loss: 0.2700 - val_acc: 0.9200
Epoch 8/1000
1599/1599 [=========================

1599/1599 [==============================] - 0s 206us/step - loss: 0.2966 - acc: 0.8881 - val_loss: 0.3663 - val_acc: 0.9050
Epoch 25/1000
1599/1599 [==============================] - 0s 220us/step - loss: 0.2872 - acc: 0.8968 - val_loss: 0.7193 - val_acc: 0.6225
Epoch 26/1000
1599/1599 [==============================] - 0s 213us/step - loss: 0.2989 - acc: 0.8906 - val_loss: 0.2879 - val_acc: 0.9200
Epoch 27/1000
1599/1599 [==============================] - 0s 173us/step - loss: 0.2880 - acc: 0.8962 - val_loss: 0.4210 - val_acc: 0.8650
Epoch 28/1000
1599/1599 [==============================] - 0s 224us/step - loss: 0.2836 - acc: 0.8987 - val_loss: 0.2979 - val_acc: 0.9200
Epoch 29/1000
1599/1599 [==============================] - 0s 187us/step - loss: 0.2622 - acc: 0.8993 - val_loss: 0.4035 - val_acc: 0.9175
Epoch 30/1000
1599/1599 [==============================] - 0s 237us/step - loss: 0.2735 - acc: 0.9012 - val_loss: 0.3829 - val_acc: 0.8875
Epoch 31/1000
1599/1599 [================

Epoch 40/1000
1600/1600 [==============================] - 0s 227us/step - loss: 0.2333 - acc: 0.9156 - val_loss: 0.4610 - val_acc: 0.8900
Epoch 41/1000
1600/1600 [==============================] - 0s 212us/step - loss: 0.2454 - acc: 0.9119 - val_loss: 0.4499 - val_acc: 0.8950
Epoch 42/1000
1600/1600 [==============================] - 0s 195us/step - loss: 0.2238 - acc: 0.9163 - val_loss: 0.4741 - val_acc: 0.9000
Epoch 43/1000
1600/1600 [==============================] - 0s 191us/step - loss: 0.2193 - acc: 0.9231 - val_loss: 0.6209 - val_acc: 0.8975
Epoch 44/1000
1600/1600 [==============================] - 0s 213us/step - loss: 0.2340 - acc: 0.9106 - val_loss: 0.6230 - val_acc: 0.8950
Epoch 45/1000
1600/1600 [==============================] - 0s 204us/step - loss: 0.2210 - acc: 0.9225 - val_loss: 0.5031 - val_acc: 0.8700
Epoch 46/1000
1600/1600 [==============================] - 0s 220us/step - loss: 0.2419 - acc: 0.9219 - val_loss: 0.4249 - val_acc: 0.8900
Epoch 47/1000
1600/1600 [==

1599/1599 [==============================] - 0s 202us/step - loss: 0.5538 - acc: 0.7448 - val_loss: 0.7588 - val_acc: 0.6375
Epoch 9/1000
1599/1599 [==============================] - 0s 236us/step - loss: 0.5497 - acc: 0.7486 - val_loss: 0.6578 - val_acc: 0.6800
Epoch 10/1000
1599/1599 [==============================] - 0s 225us/step - loss: 0.5417 - acc: 0.7536 - val_loss: 0.6526 - val_acc: 0.6725
Epoch 11/1000
1599/1599 [==============================] - 0s 223us/step - loss: 0.5315 - acc: 0.7480 - val_loss: 0.6933 - val_acc: 0.6400
Epoch 12/1000
1599/1599 [==============================] - 0s 220us/step - loss: 0.5404 - acc: 0.7624 - val_loss: 0.6536 - val_acc: 0.6700
Epoch 13/1000
1599/1599 [==============================] - 0s 200us/step - loss: 0.5253 - acc: 0.7611 - val_loss: 0.6328 - val_acc: 0.6750
Epoch 14/1000
1599/1599 [==============================] - 0s 178us/step - loss: 0.5139 - acc: 0.7636 - val_loss: 0.7491 - val_acc: 0.6600
Epoch 15/1000
1599/1599 [=================

Epoch 34/1000
1600/1600 [==============================] - 0s 193us/step - loss: 0.4047 - acc: 0.8175 - val_loss: 0.7481 - val_acc: 0.7150
Epoch 35/1000
1600/1600 [==============================] - 0s 183us/step - loss: 0.3828 - acc: 0.8356 - val_loss: 0.8207 - val_acc: 0.7050

9.2)Test loss of feature:气促_加重期 Fold:2 : 0.9420948773175031
9.2)Test accuracy of feature:气促_加重期 Fold:2 : 0.6776776778566707




Train on 1599 samples, validate on 400 samples
Epoch 1/1000
1599/1599 [==============================] - 3s 2ms/step - loss: 0.6509 - acc: 0.6542 - val_loss: 0.6310 - val_acc: 0.6750
Epoch 2/1000
1599/1599 [==============================] - 0s 286us/step - loss: 0.6124 - acc: 0.6804 - val_loss: 0.5893 - val_acc: 0.6750
Epoch 3/1000
1599/1599 [==============================] - 1s 365us/step - loss: 0.6075 - acc: 0.6779 - val_loss: 0.5954 - val_acc: 0.6750
Epoch 4/1000
1599/1599 [==============================] - 0s 307us/step - loss: 0.5958 - acc: 0.6779 - val_loss: 0.6081 - val_acc: 0.6

1599/1599 [==============================] - 0s 194us/step - loss: 0.5173 - acc: 0.7061 - val_loss: 0.6736 - val_acc: 0.5850
Epoch 19/1000
1599/1599 [==============================] - 0s 189us/step - loss: 0.4968 - acc: 0.7286 - val_loss: 0.6809 - val_acc: 0.6625
Epoch 20/1000
1599/1599 [==============================] - 0s 204us/step - loss: 0.5005 - acc: 0.7205 - val_loss: 0.7833 - val_acc: 0.6800
Epoch 21/1000
1599/1599 [==============================] - 0s 190us/step - loss: 0.4900 - acc: 0.7198 - val_loss: 0.6429 - val_acc: 0.6650
Epoch 22/1000
1599/1599 [==============================] - 0s 183us/step - loss: 0.4702 - acc: 0.7398 - val_loss: 0.7937 - val_acc: 0.6825
Epoch 23/1000
1599/1599 [==============================] - 0s 206us/step - loss: 0.4922 - acc: 0.7230 - val_loss: 0.7148 - val_acc: 0.6200
Epoch 24/1000
1599/1599 [==============================] - 0s 196us/step - loss: 0.4727 - acc: 0.7380 - val_loss: 0.8545 - val_acc: 0.5650
Epoch 25/1000
1599/1599 [================

Epoch 6/1000
1599/1599 [==============================] - 0s 196us/step - loss: 0.6564 - acc: 0.6129 - val_loss: 0.6912 - val_acc: 0.6175
Epoch 7/1000
1599/1599 [==============================] - 0s 184us/step - loss: 0.6407 - acc: 0.6248 - val_loss: 0.6755 - val_acc: 0.6175
Epoch 8/1000
1599/1599 [==============================] - 0s 190us/step - loss: 0.6377 - acc: 0.6335 - val_loss: 0.6569 - val_acc: 0.6125
Epoch 9/1000
1599/1599 [==============================] - 0s 183us/step - loss: 0.6270 - acc: 0.6517 - val_loss: 0.6948 - val_acc: 0.6100
Epoch 10/1000
1599/1599 [==============================] - 0s 186us/step - loss: 0.6227 - acc: 0.6479 - val_loss: 0.6749 - val_acc: 0.6150
Epoch 11/1000
1599/1599 [==============================] - 0s 191us/step - loss: 0.6173 - acc: 0.6560 - val_loss: 0.6897 - val_acc: 0.6175
Epoch 12/1000
1599/1599 [==============================] - 0s 186us/step - loss: 0.5953 - acc: 0.6635 - val_loss: 0.6976 - val_acc: 0.6175
Epoch 13/1000
1599/1599 [======

Epoch 26/1000
1599/1599 [==============================] - 0s 186us/step - loss: 0.4893 - acc: 0.7536 - val_loss: 1.0538 - val_acc: 0.6275
Epoch 27/1000
1599/1599 [==============================] - 0s 196us/step - loss: 0.4749 - acc: 0.7630 - val_loss: 1.0839 - val_acc: 0.6100
Epoch 28/1000
1599/1599 [==============================] - 0s 186us/step - loss: 0.4535 - acc: 0.7799 - val_loss: 1.0941 - val_acc: 0.6300
Epoch 29/1000
1599/1599 [==============================] - 0s 191us/step - loss: 0.4693 - acc: 0.7686 - val_loss: 1.1566 - val_acc: 0.5250
Epoch 30/1000
1599/1599 [==============================] - 0s 191us/step - loss: 0.4574 - acc: 0.7824 - val_loss: 1.0857 - val_acc: 0.6325
Epoch 31/1000
1599/1599 [==============================] - 0s 197us/step - loss: 0.4583 - acc: 0.7842 - val_loss: 1.0866 - val_acc: 0.5875
Epoch 32/1000
1599/1599 [==============================] - 0s 189us/step - loss: 0.4437 - acc: 0.7824 - val_loss: 0.9642 - val_acc: 0.6075
Epoch 33/1000
1599/1599 [==

1599/1599 [==============================] - 0s 168us/step - loss: 0.5927 - acc: 0.6548 - val_loss: 0.7306 - val_acc: 0.5650
Epoch 13/1000
1599/1599 [==============================] - 0s 171us/step - loss: 0.5840 - acc: 0.6698 - val_loss: 0.8509 - val_acc: 0.5575
Epoch 14/1000
1599/1599 [==============================] - 0s 167us/step - loss: 0.5730 - acc: 0.6760 - val_loss: 0.7326 - val_acc: 0.5500
Epoch 15/1000
1599/1599 [==============================] - 0s 170us/step - loss: 0.5580 - acc: 0.6842 - val_loss: 1.0301 - val_acc: 0.5500
Epoch 16/1000
1599/1599 [==============================] - 0s 167us/step - loss: 0.5711 - acc: 0.6904 - val_loss: 0.7511 - val_acc: 0.5350
Epoch 17/1000
1599/1599 [==============================] - 0s 169us/step - loss: 0.5529 - acc: 0.6854 - val_loss: 0.7735 - val_acc: 0.5950
Epoch 18/1000
1599/1599 [==============================] - 0s 186us/step - loss: 0.5409 - acc: 0.7092 - val_loss: 0.8535 - val_acc: 0.5600
Epoch 19/1000
1599/1599 [================

Epoch 35/1000
1599/1599 [==============================] - 0s 215us/step - loss: 0.4418 - acc: 0.7811 - val_loss: 1.0355 - val_acc: 0.5525
Epoch 36/1000
1599/1599 [==============================] - 0s 212us/step - loss: 0.4397 - acc: 0.7598 - val_loss: 1.3270 - val_acc: 0.5450
Epoch 37/1000
1599/1599 [==============================] - 0s 187us/step - loss: 0.4202 - acc: 0.7799 - val_loss: 1.5194 - val_acc: 0.5525

12.1)Test loss of feature:胸痛_加重期 Fold:1 : 1.5836525268554686
12.1)Test accuracy of feature:胸痛_加重期 Fold:1 : 0.589




Train on 1600 samples, validate on 400 samples
Epoch 1/1000
1600/1600 [==============================] - 3s 2ms/step - loss: 0.7204 - acc: 0.5275 - val_loss: 0.6915 - val_acc: 0.5150
Epoch 2/1000
1600/1600 [==============================] - 0s 173us/step - loss: 0.6928 - acc: 0.5306 - val_loss: 0.6811 - val_acc: 0.5425
Epoch 3/1000
1600/1600 [==============================] - 0s 173us/step - loss: 0.6897 - acc: 0.5381 - val_loss: 0.6745 - val_acc: 0.5775
Epoch 

1599/1599 [==============================] - 0s 198us/step - loss: 0.4211 - acc: 0.8130 - val_loss: 0.6464 - val_acc: 0.7625
Epoch 22/1000
1599/1599 [==============================] - 0s 173us/step - loss: 0.4037 - acc: 0.8149 - val_loss: 0.6671 - val_acc: 0.7550
Epoch 23/1000
1599/1599 [==============================] - 0s 172us/step - loss: 0.3895 - acc: 0.8224 - val_loss: 0.6991 - val_acc: 0.7050
Epoch 24/1000
1599/1599 [==============================] - 0s 173us/step - loss: 0.3820 - acc: 0.8293 - val_loss: 0.7536 - val_acc: 0.7250
Epoch 25/1000
1599/1599 [==============================] - 0s 180us/step - loss: 0.3813 - acc: 0.8268 - val_loss: 0.8188 - val_acc: 0.7725
Epoch 26/1000
1599/1599 [==============================] - 0s 229us/step - loss: 0.3759 - acc: 0.8330 - val_loss: 0.7697 - val_acc: 0.7150
Epoch 27/1000
1599/1599 [==============================] - 0s 176us/step - loss: 0.3775 - acc: 0.8186 - val_loss: 0.7960 - val_acc: 0.7575
Epoch 28/1000
1599/1599 [================

Epoch 5/1000
1600/1600 [==============================] - 0s 193us/step - loss: 0.5692 - acc: 0.7419 - val_loss: 0.5304 - val_acc: 0.7875
Epoch 6/1000
1600/1600 [==============================] - 0s 195us/step - loss: 0.5629 - acc: 0.7381 - val_loss: 0.5245 - val_acc: 0.7850
Epoch 7/1000
1600/1600 [==============================] - 0s 196us/step - loss: 0.5485 - acc: 0.7494 - val_loss: 0.5192 - val_acc: 0.7850
Epoch 8/1000
1600/1600 [==============================] - 0s 193us/step - loss: 0.5438 - acc: 0.7456 - val_loss: 0.5307 - val_acc: 0.7875
Epoch 9/1000
1600/1600 [==============================] - 0s 194us/step - loss: 0.5405 - acc: 0.7556 - val_loss: 0.5391 - val_acc: 0.7725
Epoch 10/1000
1600/1600 [==============================] - 0s 245us/step - loss: 0.5333 - acc: 0.7488 - val_loss: 0.5305 - val_acc: 0.7775
Epoch 11/1000
1600/1600 [==============================] - 0s 205us/step - loss: 0.5197 - acc: 0.7569 - val_loss: 0.6463 - val_acc: 0.6500
Epoch 12/1000
1600/1600 [=======

Epoch 31/1000
1599/1599 [==============================] - 0s 172us/step - loss: 0.3322 - acc: 0.8505 - val_loss: 0.7483 - val_acc: 0.6500
Epoch 32/1000
1599/1599 [==============================] - 0s 171us/step - loss: 0.3204 - acc: 0.8543 - val_loss: 0.8045 - val_acc: 0.7525
Epoch 33/1000
1599/1599 [==============================] - 0s 173us/step - loss: 0.3283 - acc: 0.8480 - val_loss: 0.8959 - val_acc: 0.7925
Epoch 34/1000
1599/1599 [==============================] - 0s 230us/step - loss: 0.3207 - acc: 0.8655 - val_loss: 0.7486 - val_acc: 0.8000
Epoch 35/1000
1599/1599 [==============================] - 0s 174us/step - loss: 0.3035 - acc: 0.8605 - val_loss: 0.8410 - val_acc: 0.8075
Epoch 36/1000
1599/1599 [==============================] - 0s 172us/step - loss: 0.2981 - acc: 0.8630 - val_loss: 0.7476 - val_acc: 0.7625
Epoch 37/1000
1599/1599 [==============================] - 0s 171us/step - loss: 0.3071 - acc: 0.8630 - val_loss: 0.7537 - val_acc: 0.7375
Epoch 38/1000
1599/1599 [==

1600/1600 [==============================] - 1s 321us/step - loss: 0.4625 - acc: 0.7806 - val_loss: 0.5065 - val_acc: 0.7675
Epoch 18/1000
1600/1600 [==============================] - 1s 351us/step - loss: 0.4658 - acc: 0.7800 - val_loss: 0.6539 - val_acc: 0.7975
Epoch 19/1000
1600/1600 [==============================] - 1s 364us/step - loss: 0.4522 - acc: 0.7756 - val_loss: 0.5626 - val_acc: 0.8000
Epoch 20/1000
1600/1600 [==============================] - 0s 300us/step - loss: 0.4523 - acc: 0.7825 - val_loss: 0.5948 - val_acc: 0.7950
Epoch 21/1000
1600/1600 [==============================] - 0s 260us/step - loss: 0.4464 - acc: 0.7812 - val_loss: 0.6059 - val_acc: 0.7400
Epoch 22/1000
1600/1600 [==============================] - 0s 214us/step - loss: 0.4509 - acc: 0.7887 - val_loss: 0.5875 - val_acc: 0.8025
Epoch 23/1000
1600/1600 [==============================] - 0s 206us/step - loss: 0.4582 - acc: 0.7925 - val_loss: 0.5408 - val_acc: 0.7975
Epoch 24/1000
1600/1600 [================

1599/1599 [==============================] - 0s 244us/step - loss: 0.5322 - acc: 0.7605 - val_loss: 0.4460 - val_acc: 0.8725
Epoch 5/1000
1599/1599 [==============================] - 0s 218us/step - loss: 0.5332 - acc: 0.7630 - val_loss: 0.3931 - val_acc: 0.8725
Epoch 6/1000
1599/1599 [==============================] - 1s 407us/step - loss: 0.5242 - acc: 0.7605 - val_loss: 0.4388 - val_acc: 0.8750
Epoch 7/1000
1599/1599 [==============================] - 0s 263us/step - loss: 0.5272 - acc: 0.7624 - val_loss: 0.3932 - val_acc: 0.8725
Epoch 8/1000
1599/1599 [==============================] - 0s 266us/step - loss: 0.5263 - acc: 0.7592 - val_loss: 0.4548 - val_acc: 0.8700
Epoch 9/1000
1599/1599 [==============================] - 1s 367us/step - loss: 0.5137 - acc: 0.7624 - val_loss: 0.4430 - val_acc: 0.8750
Epoch 10/1000
1599/1599 [==============================] - 0s 300us/step - loss: 0.5137 - acc: 0.7642 - val_loss: 0.3929 - val_acc: 0.8700
Epoch 11/1000
1599/1599 [=====================

Epoch 31/1000
1600/1600 [==============================] - 0s 285us/step - loss: 0.4434 - acc: 0.7906 - val_loss: 0.7045 - val_acc: 0.7525
Epoch 32/1000
1600/1600 [==============================] - 0s 296us/step - loss: 0.4438 - acc: 0.7981 - val_loss: 0.8077 - val_acc: 0.7150
Epoch 33/1000
1600/1600 [==============================] - 0s 289us/step - loss: 0.4290 - acc: 0.7963 - val_loss: 0.7612 - val_acc: 0.7675
Epoch 34/1000
1600/1600 [==============================] - 1s 352us/step - loss: 0.4228 - acc: 0.8031 - val_loss: 0.6750 - val_acc: 0.7650
Epoch 35/1000
1600/1600 [==============================] - 0s 277us/step - loss: 0.4103 - acc: 0.8063 - val_loss: 0.8425 - val_acc: 0.7675
Epoch 36/1000
1600/1600 [==============================] - 1s 315us/step - loss: 0.4155 - acc: 0.8156 - val_loss: 0.8926 - val_acc: 0.7300

15.2)Test loss of feature:双下肢水肿_加重期 Fold:2 : 0.8458838391232419
15.2)Test accuracy of feature:双下肢水肿_加重期 Fold:2 : 0.7167167168360453






# k-fold各fold数据各自模型上跑的结果

In [40]:
scoreMatrix = np.array(matrix_score_mention)[:,:,1]
print(scoreMatrix)

[[0.88       0.907      0.86586587]
 [0.838      0.856      0.82882883]
 [0.553      0.691      0.63063063]
 [0.782      0.766      0.75975976]
 [0.902      0.879      0.83883884]
 [0.696      0.691      0.67767768]
 [0.582      0.683      0.63863864]
 [0.597      0.632      0.57457457]
 [0.885      0.896      0.76476476]
 [0.707      0.718      0.67767768]
 [0.604      0.624      0.58458458]
 [0.619      0.616      0.62962963]
 [0.539      0.589      0.55755756]
 [0.696      0.743      0.74374374]
 [0.717      0.773      0.76576577]
 [0.699      0.729      0.71671672]]


In [41]:
meanScore_feature = np.mean(scoreMatrix,1)
print(meanScore_feature)

[0.88428862 0.84094294 0.62487688 0.76925325 0.87327961 0.68822589
 0.63454621 0.60119152 0.84858825 0.70089256 0.60419486 0.62154321
 0.56185252 0.72758125 0.75192192 0.71490557]


In [42]:
print(meanScore_feature.mean())

0.7155053178532434


In [35]:
print(np.array(matrix_score_mention)[:,2,1])

[0.94594595 0.87787788 0.74874875 0.74774775 0.93493494 0.77277277
 0.79179179 0.69269269 0.86886887 0.73173173 0.72872873 0.58858859
 0.69269269 0.77677678 0.81181181 0.82282282]


# k-fold在同一模型上训练结果

In [36]:
sum_df = pd.DataFrame({'症状名称':list_nodeName,
                      '是否提及准确率':np.array(matrix_score_mention)[:,2,1]})
                      
print(sum_df)

             症状名称   是否提及准确率
0        经常咳嗽_稳定期  0.945946
1        经常喘息_稳定期  0.877878
2        经常胸闷_稳定期  0.748749
3     经常活动后气促_稳定期  0.747748
4        经常咳痰_稳定期  0.934935
5          咳嗽_加重期  0.772773
6          咳痰_加重期  0.791792
7          胸闷_加重期  0.692693
8          喘息_加重期  0.868869
9          气促_加重期  0.731732
10         咯血_加重期  0.728729
11         发热_加重期  0.588589
12         胸痛_加重期  0.692693
13         心悸_加重期  0.776777
14  夜间阵发性呼吸困难_加重期  0.811812
15      双下肢水肿_加重期  0.822823


In [37]:
print(sum_df.mean())

是否提及准确率    0.783408
dtype: float64
